### PR TITLE
Added css margin for the add button on the page of Accounts.

### PR DESCRIPTION
**Pull request by yura121**
It was
2015_09_11_ffc7

and now
2015_09_11_e451

### CODE REVIEW

**Comment by 3axap4eHko** [comment]
Thanks a lot for participation. This is worst practice to change original files of a framework. Put your changes into `src\css\options.css` please

**Comment by yura121** [comment]
Really. Thank you for your patience. Fixed. Moved changes to the file <code>src\css\options.css</code>

**Comment by yura121** [comment]
Can I reopen this Pull requests or need to create a new one?

**Comment by yura121** [comment]
It seems that it is impossible. Created new one.

**Comment by 3axap4eHko** [comment]
As you whist

**Pull request closed without merging**
